-- =========================================================================
-- KMCE Pathyakram - Initial Seed Data
-- Pre-populated JNTUH R25 curriculum, faculty, question papers, and attendance
-- =========================================================================

-- Clear existing data
TRUNCATE TABLE quiz_results, attendance, documents, notifications, courses, faculty, students CASCADE;

-- 1. Insert Faculty Records
INSERT INTO faculty (id, emp_id, name, designation, department, is_hod, email, phone, photo, qualification, experience_years, office_location, assigned_subjects, research_areas) VALUES
('fac-1', 'KMCE-CSE-001', 'Dr. P. Murali Krishna', 'Professor & Head of Department (HOD)', 'CSE', TRUE, 'hod.cse@kmce.edu.in', '+91 98480 12345', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400', 'Ph.D in Computer Science (IIT Madras), M.Tech (JNTUH)', 19, 'Academic Block-A, 2nd Floor, Room A-204', '["Design & Analysis of Algorithms (CS402PC)", "Advanced Data Structures (CS301PC)"]', '["Algorithmic Complexity", "Distributed Cloud Computing", "Graph Neural Networks"]'),
('fac-2', 'KMCE-CSM-001', 'Dr. S. Radhika Devi', 'Professor & Head of Department (HOD)', 'CSM', TRUE, 'hod.csm@kmce.edu.in', '+91 94401 98765', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400', 'Ph.D in AI & Machine Learning (NIT Warangal), M.Tech', 16, 'Center for AI Excellence, 3rd Floor, Room C-302', '["Machine Learning (AI501PC)", "Deep Learning & Neural Architectures (AI602PC)"]', '["Computer Vision", "Deep Generative Models", "Explainable AI (XAI)"]'),
('fac-3', 'KMCE-ECE-001', 'Dr. K. Venkat Rao', 'Professor & Head of Department (HOD)', 'ECE', TRUE, 'hod.ece@kmce.edu.in', '+91 98765 43210', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400', 'Ph.D in VLSI Design (Osmania University), M.Tech', 22, 'Electronics Wing, 1st Floor, Room E-108', '["Digital Signal Processing (EC501PC)", "VLSI Design & Embedded Systems (EC601PC)"]', '["Low Power VLSI", "FPGA Prototyping", "Wireless Sensor Networks"]'),
('fac-4', 'KMCE-CSE-004', 'Prof. Ananya Varma', 'Associate Professor', 'CSE', FALSE, 'ananya.varma@kmce.edu.in', '+91 91234 56780', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400', 'M.Tech (CSE - JNTUH), Ph.D (Pursuing - BITS Pilani)', 11, 'Academic Block-A, Room A-212', '["Database Management Systems (CS403PC)", "Operating Systems (CS404PC)"]', '["Database Query Optimization", "Big Data Streaming", "Cloud DBs"]');

-- 2. Insert Students
INSERT INTO students (id, hallticket, name, branch, semester, academic_year, section, email) VALUES
('stu-1', '23KM1A0542', 'V. Sahith Reddy', 'CSE', 4, '2024-25', 'CSE-A', '23km1a0542@kmce.edu.in'),
('stu-2', '23KM1A6615', 'N. Sai Teja', 'CSM', 4, '2024-25', 'CSM-A', '23km1a6615@kmce.edu.in'),
('stu-3', '23KM1A0418', 'P. Sneha', 'ECE', 4, '2024-25', 'ECE-B', '23km1a0418@kmce.edu.in');

-- 3. Insert Academic Documents & Question Papers
INSERT INTO documents (id, title, type, branch, semester, subject_code, subject_name, academic_year, exam_type, uploaded_by, uploader_emp_id, upload_date, file_size, file_url, download_count, description, curriculum, exam_date, syllabus_covered, questions_preview) VALUES
('doc-1', 'Design & Analysis of Algorithms - Mid-1 Question Paper', 'question_paper', 'CSE', 4, 'CS402PC', 'Design and Analysis of Algorithms', '2024-25', 'Mid-1', 'Dr. P. Murali Krishna (HOD - CSE)', 'KMCE-CSE-001', '2025-02-14', '2.4 MB', '/documents/DAA_Mid1_2025.pdf', 382, 'Official JNTUH R25 Mid-1 Question Paper covering Asymptotic Notations, Divide and Conquer, and Dynamic Programming principles.', 'R25', '2025-02-10', 'Units 1 and 2: Asymptotic analysis, Recurrence relations, Divide & Conquer (Merge/Quick Sort), Greedy method intro.', '{"sectionA": ["Define Big-O and Little-o notations with formal mathematical limits.", "State Master Theorem for divide-and-conquer recurrences with edge cases.", "Compare greedy choice property vs optimal substructure.", "Formulate the recurrence relation for Strassen matrix multiplication."], "sectionB": [{"qNum": "Q1 (a)", "text": "Solve the recurrence T(n) = 3T(n/4) + cn^2 using Master Theorem method and recursion tree method.", "marks": 5}, {"qNum": "Q1 (b)", "text": "Explain Huffman Coding algorithm and find optimal prefix codes for {a:45, b:13, c:12, d:16, e:9, f:5}.", "marks": 5}]}'),
('doc-2', 'Machine Learning Foundations - Mid-1 Question Paper', 'question_paper', 'CSM', 4, 'AI401PC', 'Machine Learning Foundations', '2024-25', 'Mid-1', 'Dr. S. Radhika Devi (HOD - CSM)', 'KMCE-CSM-001', '2025-02-16', '3.1 MB', '/documents/ML_Mid1_2025.pdf', 418, 'JNTUH R25 CSM curriculum exam focusing on Supervised Learning, Cost Functions, Regularization, and Gradient Descent.', 'R25', '2025-02-12', 'Units 1 and 2: Linear Regression, Logistic Regression, Loss Functions, Gradient Descent Variants, Overfitting and Regularization (L1/L2).', '{"sectionA": ["Explain Bias-Variance tradeoff with appropriate graphical representation.", "Why is MSE not suitable as a loss function for Logistic Regression?", "Differentiate between Batch Gradient Descent and Stochastic Gradient Descent (SGD).", "Explain L1 (Lasso) vs L2 (Ridge) regularization penalty terms."], "sectionB": [{"qNum": "Q1 (a)", "text": "Derive the closed-form Normal Equation for Multivariate Linear Regression theta = (X^T X)^-1 X^T y.", "marks": 5}, {"qNum": "Q1 (b)", "text": "Explain decision tree splitting metrics (Entropy, Information Gain, and Gini Impurity).", "marks": 5}]}'),
('doc-3', 'Microprocessors & Microcontrollers - Mid-1 Exam Paper', 'question_paper', 'ECE', 4, 'EC403PC', 'Microprocessors & Microcontrollers', '2024-25', 'Mid-1', 'Dr. K. Venkat Rao (HOD - ECE)', 'KMCE-ECE-001', '2025-02-15', '2.8 MB', '/documents/MPMC_Mid1_2025.pdf', 290, 'Comprehensive question paper covering 8086 Microprocessor architecture, addressing modes, and 8051 microcontroller hardware.', 'R25', '2025-02-11', 'Units 1 and 2: 8086 Internal Architecture, Bus Interface Unit (BIU), Execution Unit (EU), Interrupts, Memory Segmentation.', '{"sectionA": ["Explain memory segmentation in 8086 microprocessor and its advantages.", "What are the flags present in 8086 flag register?", "Explain physical address generation formula in 8086.", "Differentiate between Microprocessor and Microcontroller architectures."], "sectionB": [{"qNum": "Q1 (a)", "text": "Draw and explain the internal architectural block diagram of 8086 microprocessor in detail.", "marks": 5}, {"qNum": "Q1 (b)", "text": "Explain various addressing modes of 8086 with assembly language examples.", "marks": 5}]}'),
('doc-4', 'Database Management Systems - Lesson Plan & Schedule', 'lesson_plan', 'CSE', 4, 'CS403PC', 'Database Management Systems', '2024-25', 'Mid-1', 'Prof. Ananya Varma', 'KMCE-CSE-004', '2025-01-08', '1.2 MB', '/documents/DBMS_LessonPlan_2025.pdf', 512, 'Unit-by-unit comprehensive lecture distribution schedule for JNTUH R25 DBMS course.', 'R25', '2025-01-06', 'All Units 1-5: ER modeling, Relational Algebra, SQL DDL/DML, Normalization (1NF to BCNF), ACID Properties, Transactions, Indexing (B+ Trees).', '{"sectionA": ["Unit 1: Entity-Relationship modeling and Relational data model", "Unit 2: SQL queries, nested subqueries, views, integrity constraints", "Unit 3: Normalization algorithms: 1NF, 2NF, 3NF, BCNF, 4NF"], "sectionB": [{"qNum": "Topic 1", "text": "Relational Calculus and Relational Algebra Equivalence rules", "marks": 0}]}');

-- 4. Insert Notifications
INSERT INTO notifications (id, title, message, category, priority, timestamp_text, read, target_branch) VALUES
('notif-1', 'JNTUH R25 Mid-1 Question Papers Released', 'Mid-1 question papers for CSE, CSM, and ECE branches have been uploaded to the Pathyakram portal with answer keys.', 'exam', 'urgent', '10 mins ago', FALSE, 'ALL'),
('notif-2', 'Attendance Warning - Condonation Threshold', 'Students whose cumulative attendance is below 75% must meet their respective departmental mentors before Friday.', 'attendance', 'high', '2 hours ago', FALSE, 'ALL'),
('notif-3', 'AI R25 Practice Quizzes Activated', 'Autonomous practice quizzes for Algorithms, Machine Learning, and Microprocessors are now live with instant AI evaluation.', 'quiz', 'normal', '1 day ago', FALSE, 'ALL');

-- 5. Insert Attendance Records
INSERT INTO attendance (id, student_hallticket, subject_code, subject_name, branch, semester, faculty_name, total_classes, attended_classes, percentage, type, last_updated) VALUES
('att-1', '23KM1A0542', 'CS402PC', 'Design & Analysis of Algorithms', 'CSE', 4, 'Dr. P. Murali Krishna', 42, 36, 85.7, 'Theory', 'Yesterday'),
('att-2', '23KM1A0542', 'CS403PC', 'Database Management Systems', 'CSE', 4, 'Prof. Ananya Varma', 38, 31, 81.5, 'Theory', 'Yesterday'),
('att-3', '23KM1A0542', 'CS404PC', 'Operating Systems', 'CSE', 4, 'Dr. B. Suresh', 40, 29, 72.5, 'Theory', '2 days ago'),
('att-4', '23KM1A0542', 'CS405PC', 'Computer Organization & Architecture', 'CSE', 4, 'Prof. K. Ramesh', 35, 28, 80.0, 'Theory', 'Yesterday'),
('att-5', '23KM1A0542', 'CS406PC', 'Algorithms & DBMS Laboratory', 'CSE', 4, 'Dr. P. Murali Krishna', 14, 13, 92.8, 'Lab', '3 days ago');

-- 6. Insert Courses
INSERT INTO courses (id, course_code, course_name, branch, semester, credits, instructor_name, instructor_emp_id, department, total_lectures, modules, reference_books) VALUES
('crs-1', 'CS402PC', 'Design and Analysis of Algorithms', 'CSE', 4, 4, 'Dr. P. Murali Krishna', 'KMCE-CSE-001', 'CSE', 48, '[{"unit": 1, "title": "Introduction & Asymptotic Analysis", "topics": ["Algorithm definition", "Order of growth", "Big-O, Omega, Theta notations", "Recurrence relations", "Master theorem"], "hours": 10}, {"unit": 2, "title": "Divide and Conquer & Greedy Method", "topics": ["Merge Sort", "Quick Sort", "Knapsack problem", "Huffman codes", "Job sequencing"], "hours": 10}, {"unit": 3, "title": "Dynamic Programming", "topics": ["0/1 Knapsack", "Matrix chain multiplication", "Longest Common Subsequence", "All-Pairs Shortest Path (Floyd-Warshall)"], "hours": 10}]', '["Introduction to Algorithms - Cormen, Leiserson, Rivest, Stein (CLRS)", "Fundamentals of Computer Algorithms - Ellis Horowitz, Sartaj Sahni"]'),
('crs-2', 'AI401PC', 'Machine Learning Foundations', 'CSM', 4, 4, 'Dr. S. Radhika Devi', 'KMCE-CSM-001', 'CSM', 50, '[{"unit": 1, "title": "Supervised Learning & Regression", "topics": ["Linear regression", "Cost functions", "Gradient descent", "Polynomial features", "Regularization (Ridge/Lasso)"], "hours": 12}, {"unit": 2, "title": "Classification Algorithms", "topics": ["Logistic regression", "Decision trees", "Random forests", "Support Vector Machines (SVM)", "Evaluation metrics"], "hours": 12}]', '["Pattern Recognition and Machine Learning - Christopher Bishop", "Hands-On Machine Learning - Aurelien Geron"]');
